In [1]:
import pandas as pd

orders = pd.read_csv("../raw_datasets/olist_orders_dataset.csv")
order_items = pd.read_csv("../raw_datasets/olist_order_items_dataset.csv")
customers = pd.read_csv("../raw_datasets/olist_customers_dataset.csv")
products = pd.read_csv("../raw_datasets/olist_products_dataset.csv")
reviews = pd.read_csv("../raw_datasets/olist_order_reviews_dataset.csv")
translation = pd.read_csv("../raw_datasets/product_category_name_translation.csv")
from datasets_prep import build_category_sentiment_dataset, build_churn_dataset, build_category_sales_forecasting_dataset

functions are fine

In [2]:
assert "order_id" in orders.columns
assert "customer_id" in customers.columns
assert "product_id" in products.columns
assert "review_comment_message" in reviews.columns

In [3]:
forecast_df = build_category_sales_forecasting_dataset(
    orders=orders,
    order_items=order_items,
    products = products,
    translation = translation
)

In [4]:

print(forecast_df.isna().sum())
print(forecast_df.shape)
forecast_df.head()

date                0
product_category    0
total_sales         0
dtype: int64
(18311, 3)

         date product_category  total_sales
0  2016-09-15    health_beauty       134.97
1  2016-10-03    fashion_shoes        29.99
2  2016-10-03  furniture_decor       194.80
3  2016-10-03   sports_leisure        58.39
4  2016-10-03             toys       128.90

In [5]:
churn_df = build_churn_dataset(
    orders=orders,
    customers=customers,
    order_items=order_items
)
churn_df.head()

,customer_unique_id,recency,frequency,monetary,r_score,f_score,m_score,rfm_risk_score,churn_risk
74,004288347e5e88a27ded2bb23747066c,106,2,317.89,2,1,3,6,Medium
98,0058f300f57d7b93c477a131a59b36c3,39,2,132.48,3,1,2,6,Medium
226,00cc12a6d8b578b8ebd21ea4e2ae8b27,405,2,99.80,1,1,1,3,High
304,011575986092c30523ecb71ff10cb473,12,2,182.90,3,1,2,6,Medium
316,011b4adcd54683b480c4d841250a987f,74,2,183.43,3,1,2,6,Medium

In [6]:
churn_df.head()
churn_df.describe()

,recency,frequency,monetary,r_score,f_score,m_score,rfm_risk_score
count,2152.000000,2152.000000,2152.000000,2152.000000,2152.000000,2152.000000,2152.000000
mean,165.804833,2.111059,257.502904,2.005576,2.000465,2.000465,6.006506
std,117.416229,0.465678,309.496277,0.817047,0.816781,0.816781,1.459178
min,0.000000,2.000000,0.000000,1.000000,1.000000,1.000000,3.000000
25%,69.000000,2.000000,109.890000,1.000000,1.000000,1.000000,5.000000
50%,147.500000,2.000000,179.255000,2.000000,2.000000,2.000000,6.000000
75%,246.000000,2.000000,301.975000,3.000000,3.000000,3.000000,7.000000
max,570.000000,10.000000,7388.000000,3.000000,3.000000,3.000000,9.000000

In [7]:
churn_df.isna().sum()

customer_unique_id    0
recency               0
frequency             0
monetary              0
r_score               0
f_score               0
m_score               0
rfm_risk_score        0
churn_risk            0
dtype: int64

In [8]:
sentiment_df = build_category_sentiment_dataset(
    reviews=reviews,
    orders=orders,
    order_items=order_items,
    products=products,
    translation=translation
)
sentiment_df.head()

,product_category,review_score,review
4,garden_tools,5,Recebi bem antes do prazo estipulado.
5,sports_leisure,5,Parabéns lojas lannister adorei comprar pela I...
13,small_appliances,4,aparelho eficiente. no site a marca do aparelh...
20,health_beauty,4,"Mas um pouco ,travando...pelo valor ta Boa.\r\n"
24,computers_accessories,5,"Vendedor confiável, produto ok e entrega antes..."

In [9]:
sentiment_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46923 entries, 4 to 112371
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_category  46923 non-null  object
 1   review_score      46923 non-null  int64
 2   review            46923 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.4+ MB

In [10]:
sentiment_df.isna().sum()

product_category    0
review_score        0
review              0
dtype: int64

In [11]:
sentiment_df[sentiment_df['product_category'].isna()]

Empty DataFrame
Columns: [product_category, review_score, review]
Index: []

In [12]:
sentiment_df["product_category"].value_counts().head()

product_category
bed_bath_table           5242
health_beauty            3751
furniture_decor          3578
sports_leisure           3438
computers_accessories    3290
Name: count, dtype: int64

In [ ]:
sentiment_df["product_category"].unique()

array(['garden_tools', 'sports_leisure', 'small_appliances',
       'health_beauty', 'computers_accessories', 'cool_stuff',
       'luggage_accessories', 'auto', 'electronics', 'watches_gifts',
       'bed_bath_table', 'pet_shop', 'perfumery', 'housewares',
       'furniture_decor', 'stationery', 'telephony', 'books_imported',
       'toys', 'baby', 'office_furniture', 'construction_tools_safety',
       'fashion_bags_accessories', 'art', 'computers',
       'christmas_supplies', 'home_appliances', 'audio', 'food_drink',
       nan, 'construction_tools_construction',
       'industry_commerce_and_business', 'musical_instruments',
       'home_confort', 'market_place', 'drinks', 'furniture_bedroom',
       'signaling_and_security', 'home_construction', 'cine_photo',
       'air_conditioning', 'books_general_interest',
       'agro_industry_and_commerce', 'furniture_mattress_and_upholstery',
       'consoles_games', 'home_appliances_2', 'home_comfort_2', 'food',
       'fashion_underwear_beach', 'small_appliances_home_oven_and_coffee',
       'books_technical', 'construction_tools_lights',
       'costruction_tools_tools', 'music', 'fashion_male_clothing',
       'fixed_telephony', 'costruction_tools_garden',
       'fashio_female_clothing', 'furniture_living_room', 'dvds_blu_ray',
       'fashion_shoes', 'cds_dvds_musicals', 'diapers_and_hygiene',
       'kitchen_dining_laundry_garden_furniture', 'party_supplies',
       'tablets_printing_image', 'flowers', 'la_cuisine', 'fashion_sport',
       'security_and_services', 'arts_and_craftmanship',
       'fashion_childrens_clothes'], dtype=object)

In [ ]:
forecast_df.to_csv('../ML_datasets/forecast_df.csv')
# sentiment_df.to_csv('../ML_datasets/sentiment_df.csv')
# churn_df.to_csv('../ML_datasets/churn_df.csv')

OSError: Cannot save file into a non-existent directory: 'ML_datasets'