In [ ]:
import pandas as pd

orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
reviews = pd.read_csv("olist_order_reviews_dataset.csv")
translation = pd.read_csv("product_category_name_translation.csv")
from prep import build_category_sentiment_dataset, build_churn_dataset, build_sales_forecasting_dataset

In [4]:
assert "order_id" in orders.columns
assert "customer_id" in customers.columns
assert "product_id" in products.columns
assert "review_comment_message" in reviews.columns

In [ ]:
forecast_df = build_sales_forecasting_dataset(
    orders=orders,
    order_items=order_items,
    products = products,
    translation = translation
)

In [6]:

print(forecast_df.isna().sum())
print(forecast_df.shape)
forecast_df.head()

date           0
total_sales    0
total_items    0
avg_freight    0
dtype: int64
(612, 4)

         date  total_sales  total_items  avg_freight
0  2016-09-15       134.97            3     2.830000
1  2016-10-03       441.98            7    16.792857
2  2016-10-04      8595.89           63    19.452857
3  2016-10-05      6169.77           48    21.661042
4  2016-10-06      5889.96           47    19.339149

In [ ]:
churn_df = build_churn_dataset(
    orders=orders,
    customers=customers,
    order_items=order_items
)
churn_df.head()

In [ ]:
churn_df.head()
churn_df.describe()

            recency     frequency      monetary  avg_delivery_delay
count  96096.000000  96096.000000  96096.000000        93356.000000
mean     287.735691      1.034809    141.438184           12.101917
std      153.414676      0.214384    217.215904            9.552425
min        0.000000      1.000000      0.000000            0.000000
25%      163.000000      1.000000     45.990000            6.000000
50%      268.000000      1.000000     89.000000           10.000000
75%      397.000000      1.000000    154.000000           15.000000
max      772.000000     17.000000  13440.000000          209.000000

In [ ]:
churn_df.isna().sum()

customer_unique_id       0
recency                  0
frequency                0
monetary                 0
avg_delivery_delay    2740
dtype: int64

In [ ]:
sentiment_df = build_category_sentiment_dataset(
    reviews=reviews,
    orders=orders,
    order_items=order_items,
    products=products,
    translation=translation
)
sentiment_df.head()

IndexError: boolean index did not match indexed array along axis 0; size of axis is 1 but size of corresponding boolean axis is 2

In [ ]:
sentiment_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47642 entries, 4 to 112371
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_category  46923 non-null  object
 1   review_score      47642 non-null  int64
 2   review            47642 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.5+ MB

In [ ]:
sentiment_df.isna().sum()

product_category    719
review_score          0
review                0
dtype: int64

In [ ]:
sentiment_df[sentiment_df['product_category'].isna()]

,product_category,review_score,review
282,NaN,1,Comprei dois produtos e recebi somente um. Man...
422,NaN,5,ótimo chegou bem antes do prazo .
518,NaN,5,Até hoje estou satisfeito com a sbmarino
716,NaN,2,parece que mantem bem o alimento sem murchar (...
726,NaN,5,Parabéns 😤 pelo excelente atendimento de quali...
...,...,...,...
111283,NaN,4,produto muito bonito e embalado com cuidado
111440,NaN,5,Eu recomendo excelente muitooooo bom entregou ...
111746,NaN,1,PRODUTO PARECE QUE JA FOI UTILIZADO FEIO TUDO ...
111747,NaN,1,PRODUTO PARECE QUE JA FOI UTILIZADO FEIO TUDO ...
112025,NaN,5,Entrega rápida e tudo certinho.

In [ ]:
sentiment_df["product_category"].value_counts().head()

product_category
bed_bath_table           5242
health_beauty            3751
furniture_decor          3578
sports_leisure           3438
computers_accessories    3290
Name: count, dtype: int64

In [ ]:
sentiment_df["product_category"].unique()

array(['garden_tools', 'sports_leisure', 'small_appliances',
       'health_beauty', 'computers_accessories', 'cool_stuff',
       'luggage_accessories', 'auto', 'electronics', 'watches_gifts',
       'bed_bath_table', 'pet_shop', 'perfumery', 'housewares',
       'furniture_decor', 'stationery', 'telephony', 'books_imported',
       'toys', 'baby', 'office_furniture', 'construction_tools_safety',
       'fashion_bags_accessories', 'art', 'computers',
       'christmas_supplies', 'home_appliances', 'audio', 'food_drink',
       nan, 'construction_tools_construction',
       'industry_commerce_and_business', 'musical_instruments',
       'home_confort', 'market_place', 'drinks', 'furniture_bedroom',
       'signaling_and_security', 'home_construction', 'cine_photo',
       'air_conditioning', 'books_general_interest',
       'agro_industry_and_commerce', 'furniture_mattress_and_upholstery',
       'consoles_games', 'home_appliances_2', 'home_comfort_2', 'food',
       'fashion_underwear_beach', 'small_appliances_home_oven_and_coffee',
       'books_technical', 'construction_tools_lights',
       'costruction_tools_tools', 'music', 'fashion_male_clothing',
       'fixed_telephony', 'costruction_tools_garden',
       'fashio_female_clothing', 'furniture_living_room', 'dvds_blu_ray',
       'fashion_shoes', 'cds_dvds_musicals', 'diapers_and_hygiene',
       'kitchen_dining_laundry_garden_furniture', 'party_supplies',
       'tablets_printing_image', 'flowers', 'la_cuisine', 'fashion_sport',
       'security_and_services', 'arts_and_craftmanship',
       'fashion_childrens_clothes'], dtype=object)

In [ ]:
image = pd.read_csv('image_category.csv')

In [ ]:
image.columns

Index(['index', 'Uniq Id', 'Crawl Timestamp', 'Category', 'Product Title',
       'Product Description', 'Brand', 'Pack Size Or Quantity', 'Mrp', 'Price',
       'Site Name', 'Offers', 'Combo Offers', 'Stock Availibility',
       'Product Asin', 'Image Urls'],
      dtype='object')

In [ ]:
print(image['Image Urls'].iloc[100])
# the seperator is |

https://images-na.ssl-images-amazon.com/images/I/414KDLGziSL._SX38_SY50_CR,0,0,38,50_.jpg|https://images-na.ssl-images-amazon.com/images/I/41K8PxnX2hL._SX38_SY50_CR,0,0,38,50_.jpg|https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/transparent-pixel._V192234675_.gif

In [ ]:
top_categories = (
    image['Category']
    .value_counts()
    .head(10)
    .index
)

image_df = image[image['Category'].isin(top_categories)]
image_df.head()

,index,Uniq Id,Crawl Timestamp,Category,Product Title,Product Description,Brand,Pack Size Or Quantity,Mrp,Price,Site Name,Offers,Combo Offers,Stock Availibility,Product Asin,Image Urls
0,0,eb49cc038190f6f03c272f79fbbce894,2019-10-30 11:38:11 +0000,Skin Care,Lee posh Lactic Acid 60% Anti ageing Pigmenta...,PROFESSIONAL GRADE Face Peel: this peel stimul...,Lee Posh,NaN,2000.00,799.00,Amazon In,60.05%,NaN,YES,B072BGHNJ1,https://images-na.ssl-images-amazon.com/images...
1,1,1657cc30c438affede6a5060d6847363,2019-10-31 15:46:54 +0000,Skin Care,Branded SLB Works New 1.5mm Titanium 1200 nee...,Item name: 1.5mm titanium 1200 needles microne...,SLB Works,NaN,2040.00,2040.00,Amazon In,0%,NaN,YES,B07QDTZYSJ,https://images-na.ssl-images-amazon.com/images...
2,2,41654633cce38c8650690f6dbac01fd3,2019-10-30 09:53:23 +0000,Skin Care,Generic 1 Pc brand snail eye cream remove dar...,"Use: eye, item type: cream, net wt: 20g, gzzz:...",Generic,NaN,1824.00,1042.00,Amazon In,42.87%,NaN,YES,B07DCSN8MP,https://images-na.ssl-images-amazon.com/images...
3,3,08b1bd85c3efc2d7aa556fd79b073382,2019-10-29 16:16:52 +0000,Skin Care,Generic Anti Snoring Snore Stopper Sleep Apne...,Prevent the tongue from dropping backward or b...,Generic,NaN,2185.00,1399.00,Amazon In,35.97%,NaN,YES,B07GLW9VQN,https://images-na.ssl-images-amazon.com/images...
4,4,3ac3f213732512d1d11bb73ab3b1900f,2019-10-31 09:32:06 +0000,Grocery & Gourmet Foods,Harveys Crunchy & Creame Gourmet Delicacies C...,Harvey's wafer Cream Wafer 110g. Made in India,Harveys,NaN,594.00,570.00,Amazon In,4.04%,NaN,YES,B07NFYYLF1,https://images-na.ssl-images-amazon.com/images...

In [ ]:
image_df['Category'].unique()

array(['Skin Care', 'Grocery & Gourmet Foods', 'Bath & Shower',
       'Fragrance', 'Hair Care', 'Detergents & Dishwash'], dtype=object)

In [ ]:
MAX_IMAGES_PER_CATEGORY = 100

image_df = (
    image_df
    .groupby('Category')
    .apply(lambda x: x.sample(
        n=min(len(x), MAX_IMAGES_PER_CATEGORY),
        random_state=42
    ))
    .reset_index(drop=True)
)

C:\Users\hello\AppData\Local\Temp\ipykernel_20404\3325695268.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(

In [ ]:
import re

def extract_high_res_image(urls):
    if pd.isna(urls):
        return None

    first_url = urls.split('|')[0]

    # Remove Amazon size modifier like ._SS40_
    high_res_url = re.sub(r'\._.*?_\.', '.', first_url)

    return high_res_url



image_df['Primary_Image'] = image_df['Image Urls'].apply(extract_high_res_image)
image_df = image_df.dropna(subset=['Primary_Image'])

In [ ]:
image_df['Primary_Image'].iloc[0]

'https://images-na.ssl-images-amazon.com/images/I/51viZOPQ%2BCL.jpg'

In [ ]:
import os
import requests

def download_images(df, category_col, url_col):
    for _, row in df.iterrows():
        category = row[category_col]
        url = row[url_col]

        folder = f"images/{category}"
        os.makedirs(folder, exist_ok=True)

        try:
            img_data = requests.get(url, timeout=10).content
            filename = os.path.join(folder, url.split("/")[-1])
            with open(filename, "wb") as f:
                f.write(img_data)
        except:
            continue

In [ ]:
download_images(image_df, "Category", "Primary_Image")

In [ ]:
from PIL import Image

def resize_images(base_dir="images", size=(224,224)):
    for category in os.listdir(base_dir):
        cat_path = os.path.join(base_dir, category)
        for img in os.listdir(cat_path):
            try:
                path = os.path.join(cat_path, img)
                image = Image.open(path).convert("RGB")
                image = image.resize(size)
                image.save(path)
            except:
                continue

In [ ]:
amazon_to_olist = {
    "Skin Care": "health_beauty",
    "Bath & Shower": "health_beauty",
    "Hair Care": "health_beauty",
    "Fragrance": "perfumery",
    "Grocery & Gourmet Foods": "food_drink",
    "Detergents & Dishwash": "housewares"
}